### ISSUE TITLE
Does it support messages to/from pages?

### ISSUE THREAD

**Issue by dpriskorn** [stalha97/Multi-Users-Chat-Messenger#1]

**Comment by stalha97** [comment]
Which pages? Messages can be sent and received using CLI. Only the given Client file can be used to send and receive messages.

**Comment by dpriskorn** [comment]
Facebook pages has their own inbox

**Comment by dpriskorn** [comment]
Try creating a page and see for yourself

**Comment by stalha97** [comment]
Unfortunately No. This project isn't related to Facebook actually. I only mentioned "it works like a Facebook messenger". It is a C++ based project and I am not sure if it can be even connected to Facebook inbox. I don't think this is the right tool for that.
